server:
  port: 8081

spring:
  application:
    name: ms-chamado-service
  datasource:
    url: jdbc:h2:mem:chamadodb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  chamado:
    default:
      situacao: PENDENTE
    notification:
      enabled: true

logging:
  level:
    com.jaime.mschamado: DEBUG
